name: autofy

services:
  db:
    image: postgres:17.2-alpine
    container_name: db
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "${DATABASE_PORT}:5432"
    volumes:
      - db:/var/lib/postgresql/data

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
    ports:
      - "5173:5173"
    command: ["bun", "dev"]  # Run `bun dev` to start the dev server


volumes:
  db:
