name: autofy

services:
  db:
    image: postgres:17.2-alpine
    container_name: db
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "${DATABASE_PORT}:5432"
    volumes:
      - db:/var/lib/postgresql/data

  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
    ports:
      - "5173:5173"
    command: ["bun", "--bun", "run", "dev"]
    profiles:
      - dev
    depends_on:
      - db

  frontend-preview:
    build:
      context: .
      dockerfile: Dockerfile.preview
    volumes:
      - .:/app
    ports:
      - "5173:4173"
    command: ["bun", "--bun", "run", "preview"]
    profiles:
      - preview
    depends_on:
      - db


volumes:
  db:
